### ISSUE TITLE
turn this repository into a template repository to facliitate re-use

### ISSUE THREAD

**Issue by jhpoelen** [seltmann/taxonomy-darwin-core#6]
Github recently introduced the idea of template repositories to overcome the limitations of restricting forks to only one per repository per account. In keeping the repository a non-template repository, individual users cannot fork the repository multiple times. 

For example, see https://github.com/globalbioticinteractions/template-dataset .  https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository .

![Screenshot from 2022-01-14 11-47-58](https://user-images.githubusercontent.com/1084872/149576187-ccbe163e-b7f4-4a7e-9328-31670da8b866.png)

**Comment by seltmann** [comment]
Turned into a template repository.

**Comment by jhpoelen** [comment]
@seltmann your template repository has been successfully indexed by GloBI . 

See e.g., 
https://www.globalbioticinteractions.org/?accordingTo=globi%3Aseltmann%2Ftaxonomy-darwin-core&interactionType=ecologicallyRelatedTo 

and attached screenshot. 

![Screenshot from 2022-01-24 09-22-59](https://user-images.githubusercontent.com/1084872/150832982-21bc1da9-154e-4531-b069-3f91544ad8bb.png)
